name: CD

# main 브랜치에 푸시될 때마다 실행
on:
  push:
    branches: [ main ]

jobs:
  deploy-to-ec2:
    name: Deploy to EC2
    runs-on: ubuntu-latest

    steps:
      # 1) 코드 체크아웃
      - uses: actions/checkout@v3

      # 2) JDK 빌드
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      # 3) JAR 빌드
      - name: Build JAR
        run: ./gradlew clean bootJar --no-daemon

      # 4) EC2로 JAR 복사
      - name: Copy JAR to EC2
        uses: appleboy/scp-action@v0.1.5
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ubuntu
          key: ${{ secrets.SSH_PRIVATE_KEY }} # GitHub Secrets에 저장된 SSH 개인 키 이름 (정확히 확인)
          source: build/libs/*.jar # 빌드된 JAR 파일 경로
          target: /home/ubuntu/app/ # EC2 서버의 목적지 경로 (사용자 이름에 따라 다를 수 있음)

      # 5) EC2에서 서비스 재시작
      - name: Restart todo.service
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ubuntu
          key: ${{ secrets.SSH_PRIVATE_KEY }} # GitHub Secrets에 저장된 SSH 개인 키 이름 (정확히 확인)
          script: |
            sudo systemctl daemon-reload
            sudo systemctl restart todo.service
            sudo systemctl status todo.service # 서비스 재시작 후 상태 확인 명령 추가 (선택 사항)